print("Enter the first number to add:")
FIRST = input()
print("Enter the second number to add:")
SECOND = input()
print("Enter the third number to add:")
THIRD = input()
print("The sum is ")
print(int(FIRST) + int(SECOND) + int(THIRD))
