print("Enter the name of cat 1:")
CAT_NAME1 = input()
print("Enter the name of cat 2:")
CAT_NAME2 = input()
print("Enter the name of cat 3:")
CAT_NAME3 = input()
print("Enter the name of cat 4:")
CAT_NAME4 = input()
print("Enter the name of cat 5:")
CAT_NAME5 = input()
print("Enter the name of cat 6:")
CAT_NAME6 = input()
print("The cat names are:")
print(CAT_NAME1 + " " + CAT_NAME2 + " " + CAT_NAME3 + " " + CAT_NAME4 + " " +
      CAT_NAME5 + " " + CAT_NAME6)
